AssignmentMVC/Controllers/LoginController.cs
using AssignmentMVC.BAL;
using AssignmentMVC.ViewModel;
using Elmah;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace AssignmentMVC.Controllers
{
    [Authorize]
    public class LoginController : Controller
    {
        /// <summary>
        /// Get for LoginView
        /// </summary>
        /// <returns>View</returns>
        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }




        /// <summary>
        /// Authenticate the USER
        /// </summary>
        /// <param name="loginModel"></param>
        /// <returns>Dashboard View</returns>
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel loginModel)
        {
            DAL logicObject = new DAL();
            int userId = logicObject.LogIn(loginModel);
            if (userId != 0)
            {
                FormsAuthentication.SetAuthCookie(loginModel.Email, false);
                return RedirectToAction("DashBoard", "User");
            }
            else
            {
                ViewBag.ErrorMessage = "Invalid Login Details.";
                return View("Login");
            }
        }
    }
}

AssignmentMVC/Controllers/RegistrationController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AssignmentMVC.BAL;
using AssignmentMVC.ViewModel;
using System.Web.Security;
using System.IO;
using AssignmentMVC.BusinessClass;

namespace AssignmentMVC.Controllers
{
    [Authorize]
    public class RegistrationController : Controller
    {
        BLL Reference = new BLL();
        DAL LogicObject = new DAL();

        /// <summary>
        /// Index Page for Website
        /// </summary>
        /// <returns>View of INDEX</returns>
        [AllowAnonymous]
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("DashBoard", "User");
            }
            return View();
        }


        /// <summary>
        /// GET the registration page Action Method.
        /// </summary>
        /// <returns>View Page for Registration</returns>
        [AllowAnonymous]
        public ActionResult Register()
        {
            return View();
        }



        /// <summary>
        /// Post Method for Creating the User and save details in the Database.
        /// </summary>
        /// <param name="registrationModel"></param>
        /// <returns>Dashboard View with Users Object</returns>
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegistrationModel registrationModel)
        {
            if (ModelState.IsValid)
            {
                for (int flag = 0; flag < registrationModel.ContactNumber.Count(); flag++)
                {
                    var checkStatus = BusinessClass.ContactValidation.ValidateContact(registrationModel.ContactNumber[flag]);
                    if (!checkStatus)
                    {
                        ViewBag.Contact = "Invalid Contact field/Fields";
                        return View("Register");
                    }
                }
                var dataObject = Reference.Users.Where(m => m.Email == registrationModel.Email).SingleOrDefault();
                if (dataObject == null)
                {
                    if (registrationModel.ImageURL == null || ((BusinessClass.ImageValidator.ImgaeValidate(Path.GetExtension(registrationModel.ImageURL.FileName))) && registrationModel.ImageURL.ContentLength <= 512000))
                    {
                        string email = LogicObject.Create(registrationModel);
                        if (email != string.Empty)
                        {
                            FormsAuthentication.GetAuthCookie(email, false);
                            return RedirectToAction("DashBoard", "User");
                        }
                        else
                        {
                            return RedirectToAction("Login");
                        }
                    }
                    else
                    {
                        ViewBag.Message = "Invalid Image Format/Size !";
                        return View("Register");
                    }
                }
                else
                {
                    ViewBag.Message = "Email Already Exists !";
                    return View("Register");
                }

            }
            else
            {
                return View("Register");
            }

        }





        /// <summary>
        /// Logout and FormAuthentication is destroyed.
        /// </summary>
        /// <returns>Removes Cookie</returns>
        public ActionResult Logout()
        {
            Session.Clear();
            Session.Abandon();
            Session.RemoveAll();
            FormsAuthentication.SignOut();
            this.Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            this.Response.Cache.SetCacheability(HttpCacheability.NoCache);
            this.Response.Cache.SetNoStore();
            return RedirectToAction("Login", "Login");
        }


        /// <summary>
        /// Method for fetching information from Database to know Emial is present or not.
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public JsonResult CheckMail(string email)
        {
            var obj = Reference.Users.Where(m => m.Email == email).SingleOrDefault();
            return obj != null ? Json(false) : Json(true);
        }

    }
}

AssignmentMVC/Views/Login/Login.cshtml
@model AssignmentMVC.ViewModel.LoginModel

@{
    ViewBag.Title = "login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-md-3">
    </div>
    <div class="col-md-6">
        @using (Html.BeginForm("Login", "Login", FormMethod.Post, new { @id = "LoginForm" }))
        {
           @Html.AntiForgeryToken()
            <h3>Login</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <p class="view-bag">@ViewBag.ErrorMessage</p>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-4 text-right">
                        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })<span class="error">*</span>
                    </div>
                    <div class="col-sm-8 input-group ">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", placeholder = "Enter your Email." } })
                    </div>
                    <div class="col-sm-offset-5 col-xs">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-4 text-right">
                        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label" })<span class="error">*</span>
                    </div>
                    <div class="col-sm-8 input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                        @Html.PasswordFor(model => model.Password, new { @class = "form-control", placeholder = "Enter your password." })
                    </div>
                    <div class="col-md-offset-5 col-xs">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-sm-8">
                    </div>
                    <div class="col-sm-4">
                        <input type="submit" style="margin-top:20px;" value="Login" class="btn btn-success" />
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-md-8">
                        <p class="direction">Don't have an Account @Html.ActionLink("Signup", "Register", "Registration") here.</p>
                    </div>
                    <div class="col-md-4">
                    </div>
                </div>
            </div>
        }
    </div>
</div>